#!/usr/bin/perl
use strict;
use warnings;
use XML::Simple;
use LWP::UserAgent;
use Term::ANSIColor qw(colored);
use Digest::SHA qw(sha256_hex);
use Data::Dumper;
use POSIX qw(strftime);

# near future feature, coming soon
my $conf_hash;

my $CONFIG = $ENV{'HOME'} . "/.vcxconf.xml";
if (-e $CONFIG) {
    $conf_hash = XMLin($CONFIG);
}

my $sleep_int = 2;

# interval checking
if (defined $ARGV[0] && $ARGV[0] =~ m/^\d{1,3}$/) {
    $sleep_int = $ARGV[0];
}


my $ua = LWP::UserAgent->new;

# whatever .. vircurex just doesn't like libwww-perl as user agent signature
$ua->agent("Mozilla/8.0");  
$ua->cookie_jar({file => "$ENV{'HOME'}/.cookiejar_vcx.txt"});   

# which coins do we want to watch?
my @watchlist = qw(DOGE FTC FRC I0C IXC NMC NVC NXT LTC DVC DGC ANC WDC TRC XPM QRK PPC);

my ($balance, $data, $response);
my ( $nowtime, $storcounter, $nowdate, $block, $runcounter, @storage, $cur, $low, $high, 
     $avg_50, $avg_500, $avg_250, $sum_500, $sum_250, $sum_50, $v, $bal, $bal_avail,
     $avg_1000, $sum_1000);


my $comp_data;
my $colcount = 0;
my $ln;
$storcounter = -1;
$runcounter = 0;

# function for getting balance information
sub get_balance {
    return 0 unless $conf_hash->{'username'};
    my $timestamp = strftime "%Y-%m-%dT%H:%M:%S", gmtime;
    my $txid = sha256_hex($timestamp);
    my $user = $conf_hash->{'username'};
    my $sec_getbal = $conf_hash->{'get_balance_word'};

    my $token = sha256_hex("$sec_getbal;$user;$timestamp;$txid;get_balances");
    $balance = 0;
    $response = $ua->get("https://api.vircurex.com/api/get_balances.xml?account=$user&id=$txid&token=$token&timestamp=$timestamp");
    if ($response->is_success) {
        $balance = eval { XMLin($response->decoded_content) };
        $balance = 0 if $@;
    }
    undef $response;
    undef $txid;
    undef $user;
    undef $sec_getbal;
    undef $token;
    system('clear');
    return $balance;
}


# function that gets th API xml file and then parses it into a wonderful hash
sub get_data {
    $data = {};
    $comp_data = {};
    $response = $ua->get("https://api.vircurex.com/api/get_info_for_currency.xml");
    if ($response->is_success) {
        $data = eval { XMLin($response->decoded_content) };
        $data = 0 if $@;
    }
    
    if ($data != 0) {
        for my $cur (@watchlist) {
            $comp_data->{$cur}{'la'} = $data->{$cur}{'BTC'}{'lowest-ask'}{'content'};
            $comp_data->{$cur}{'hb'} = $data->{$cur}{'BTC'}{'highest-bid'}{'content'};
            $comp_data->{$cur}{'lt'} = $data->{$cur}{'BTC'}{'last-trade'}{'content'};
            $comp_data->{$cur}{'vo'} = $data->{'BTC'}{$cur}{'volume'}{'content'};
        }
    }
    undef $data;
    undef $response;
    return $comp_data;
}
sub is_lt { return $_[0] < -10.0 ? 1 : 0; }
sub is_gt { return $_[0] > 10.0 ? 1 : 0; }
sub is_positive { return $_[0] > 0.0 ? 1 : 0; }
sub is_zero { return $_[0] == 0.0 ? 1 : 0; }

sub formprint {
    my $need_separator = shift;
    if ($colcount % 2) {
        if (is_gt($_[0])) {             printf ("%9s",  colored($_[0], 'bold green on_black'));   }
        elsif (is_positive($_[0])) {    printf ("%9s",  colored($_[0], 'bright_green on_black')); }
        elsif (is_lt($_[0])) {          printf ("%9s",  colored($_[0], 'bold red on_black'));     }
        elsif (is_zero($_[0])) {        printf ("%9s",  colored($_[0], 'bright_white on_black')); }
        else {                          printf ("%9s",  colored($_[0], 'bright_red on_black'));   }
    }
    else { 
        if (is_gt($_[0])) {             printf ("%9s",  colored($_[0], 'bold green on_grey3'));   }
        elsif (is_positive($_[0])) {    printf ("%9s",  colored($_[0], 'bright_green on_grey3')); }
        elsif (is_lt($_[0])) {          printf ("%9s",  colored($_[0], 'bold red on_grey3'));     }
        elsif (is_zero($_[0])) {        printf ("%9s",  colored($_[0], 'bright_white on_grey3')); }
        else {                          printf ("%9s",  colored($_[0], 'bright_red on_grey3'));   }
    }
    if ($need_separator) {
        if ($colcount % 2) {
            print colored("  :  ", 'bright_white on_black');
        }
        else {
            print colored("  :  ", 'bright_white on_grey3');
        }
    }
}


while (1) {
    # date and time
    $nowdate = sprintf("%02d-%02d-%02d", (localtime)[3], (localtime)[4] + 1, (localtime)[5] + 1900);
    $nowtime = sprintf("%02d:%02d:%02d", (localtime)[2], (localtime)[1], (localtime)[0]);
    $block = get_data();
    $bal = get_balance();
    $bal_avail = 0;

    if ($bal != 0) { $bal_avail = 1; }

    if ($block != {}) {
        push @storage, $block;
        $storcounter++;
        $runcounter++;
    }
    if (scalar @storage > 1000) { # 1000 times x secs for averages and tendencies
        undef $storage[0];
        shift @storage;
        $storcounter--;
    }

    print "$nowdate - $nowtime - refresh approx. every $sleep_int seconds (+ some seconds [network/load]) [ ", sprintf("%09d", $runcounter), " polls ]";
    print "\nHB - highest bid / LA - lowest ask / LT - last executed trade / VOL_BTC - Trading Volume in BTC\n";
    print "TENDENCY is a percentual value and will appear after some time, please be patient :)\n";
    print "Tendency calculates like this: (last_trade / average_of_x_recorded_trades * 100) - 100\n\n";
    printf("%8s  :  %10s  :  %10s  :  %10s  :  %10s  :  %10s  :  %10s  :  %10s  :  %10s\n\n\n", qw(CUR HB LA LT VOL_BTC TEND_50 TEND_250 TEND_500 TEND_1000));
    $colcount = 0;
    if ($storcounter >= 0 ) {
        for my $cur (sort keys %{$storage[$storcounter]}) {
            $colcount++;
            $ln = sprintf "%8s  :  %.8f  :  %.8f  :  %.8f  :  %010.5f  :  ", 
            $cur, $storage[scalar @storage - 1]->{$cur}{'hb'}, $storage[scalar @storage - 1]->{$cur}{'la'},
            $storage[scalar @storage - 1]->{$cur}{'lt'}, $storage[scalar @storage - 1]->{$cur}{'vo'};
            if ($colcount % 2) {
                print colored($ln, 'bright_white on_black');
            }
            else {
                print colored($ln, 'bright_white on_grey3');
            }
            if (scalar @storage >= 50) {
                ($low, $high) = (scalar @storage - 50, scalar @storage - 1);
                $sum_50 = 0.0;
                for my $c($low .. $high) {
                    $sum_50 += $storage[$c]->{$cur}{'lt'} if $storage[$c]->{$cur}{'lt'};
                }
                $avg_50 = $sum_50 / 50;
                $v = sprintf("%+010.5f", ($storage[$high]->{$cur}{'lt'} / $avg_50 * 100) - 100);
                formprint(1, $v);
                if (scalar @storage >= 250) {
                    ($low, $high) = (scalar @storage - 250, scalar @storage - 1);
                    $sum_250 = 0.0;
                    for my $c ($low .. $high) {
                        $sum_250 += $storage[$c]->{$cur}{'lt'} if $storage[$c]->{$cur}{'lt'};
                    }
                    $avg_250 = $sum_250 / 250;
                    $v = sprintf("%+010.5f", ($storage[$high]->{$cur}{'lt'} / $avg_250 * 100) - 100);
                    formprint(1, $v);
                    if (scalar @storage >= 500) {
                        ($low, $high) = (scalar @storage - 500, scalar @storage - 1);
                        $sum_500 = 0.0;
                        for my $c ($low .. $high) {
                            $sum_500 += $storage[$c]->{$cur}{'lt'} if $storage[$c]->{$cur}{'lt'};
                        }
                        $avg_500 = $sum_500 / 500;
                        $v = sprintf("%+010.5f", ($storage[$high]->{$cur}{'lt'} / $avg_500 * 100) - 100);
                        formprint(1, $v);
                        if (scalar @storage >= 1000) {
                            ($low, $high) = (scalar @storage - 1000, scalar @storage - 1);
                            $sum_1000 = 0.0;
                            for my $c ($low .. $high) {
                                $sum_1000 += $storage[$c]->{$cur}{'lt'} if $storage[$c]->{$cur}{'lt'};
                            }
                            $avg_1000 = $sum_1000 / 1000;
                            $v = sprintf("%+010.5f", ($storage[$high]->{$cur}{'lt'} / $avg_1000 * 100) - 100);
                            formprint(0, $v);
                        }
                    }

                }
                print " %\n";
            }
            else {
                print "\n";
            }

        }
        print "\n";
    }
    print "\n\n\tBALANCES\n\n";
    printf "%5s: %20s %20s\n\n", "CUR", "TOTAL BALANCE", "AVAIL BALANCE";
    $colcount = 0;
    if ($bal_avail) {
        for (sort keys %{$bal->{'balances'}}) {
            $ln = sprintf "%5s: %20.8f %20.8f\n", $_ ,$bal->{'balances'}{$_}{'balance'}{'content'}, $bal->{'balances'}{$_}{'availablebalance'}{'content'};
            $colcount++;
            if ($colcount % 2) {
                print colored($ln, 'bright_white on_black');
            }
            else {
                print colored($ln, 'bright_white on_grey3');
            }
        }
    }

    print colored ("\n\nIf you like this program and want to give me some credit for it, please donate to my LTC adress: LbD7yPykMXhP83tH7PNoDL63YEujXDxxBC\n", 'italic white on_black');
    sleep $sleep_int;
}
